package com.mythstack.registry;

import com.mythstack.MythStack;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.biome.v1.ModificationPhase;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.biome.Biomes;
import net.minecraft.world.level.levelgen.GenerationStep;

import java.util.List;

/**
 * Geology overhaul (STONE_PHASE.md, worldgen): the code half. The data half — regional base
 * stones, sand/ice bands, permafrost — lives in the noise-settings override generated by
 * {@code scripts/gen_worldgen.py}. Here: the vanilla granite/diorite/andesite/tuff mini-blob
 * features are removed (regions replace them), and blue ice veins seed the tundra ice band.
 */
public final class ModWorldgen {
	private ModWorldgen() {
	}

	public static void register() {
		BiomeModifications.create(MythStack.id("remove_stone_blobs"))
				.add(ModificationPhase.REMOVALS, BiomeSelectors.all(), context -> {
					for (String feature : List.of("ore_granite_lower", "ore_granite_upper",
							"ore_diorite_lower", "ore_diorite_upper",
							"ore_andesite_lower", "ore_andesite_upper", "ore_tuff")) {
						context.getGenerationSettings().removeFeature(ResourceKey.create(
								Registries.PLACED_FEATURE, Identifier.withDefaultNamespace(feature)));
					}
				});
		BiomeModifications.addFeature(
				BiomeSelectors.includeByKey(Biomes.SNOWY_PLAINS, Biomes.ICE_SPIKES, Biomes.SNOWY_TAIGA),
				GenerationStep.Decoration.UNDERGROUND_ORES,
				ResourceKey.create(Registries.PLACED_FEATURE, MythStack.id("blue_ice_vein")));
	}
}
